name: Sample Workflow

on:
  push:
    branches:
      - master

jobs:
  checkout-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test
        run: |
          echo "$(git describe --abbrev=0 --tags)"
          echo "$(git describe --tags `git rev-list --tags --max-count=1`)"
          echo "${git describe --tags `git rev-list --tags --max-count=1`}"
      - name: Fetch Latest Tag
        id: fetch-tag
        run: |
          echo "TAG_NAME=$(git rev-list --tags --skip=0 --max-count=1)" >> $GITHUB_OUTPUT

      - run: |
          echo "${{ steps.fetch-tag.outputs.TAG_NAME }}"

      - name: Checkout with Hash
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.fetch-tag.outputs.TAG_NAME }}
