name: Sample Workflow

on:
  push:
    branches:
      - master

jobs:
  checkout-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with Hash
        id: checkout-hash
        uses: actions/checkout@v3
        with:
          ref: $(git rev-list --tags --skip=0 --max-count=1)

  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Latest Release
        id: latest-release
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Latest Release source code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.latest-release.outputs.tag-name }}

      - name: Debugging
        run: echo ${{ steps.latest-release.outputs.tag-name }}
