name: Sample Workflow

on:
  push:
    branches:
      - master

jobs:
  checkout-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Latest Tag
        id: fetch-tag
        run: echo "::set-output name=ref::$(git rev-list --tags --skip=0 --max-count=1)"
      
      - run: ${{ steps.fetch-tag.outputs.ref }}

      - name: Checkout with Hash
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.fetch-tag.outputs.ref }}
