name: Sample Workflow

on:
  push:
    branches:
      - master

jobs:
  stage1:
    runs-on: ubuntu-latest
    steps:
      - name: stage1 step(1)
        run: echo "stage1"

  rollback:
    runs-on: ubuntu-latest
    needs: stage1
    steps:
      - name: Fetch Latest Release
        id: latest-release
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Latest Release source code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.latest-release.outputs.tag-name }}

      - name: Debugging
        run: echo ${{ steps.latest-release.outputs.tag-name }}
