name: Auto Release

on: [pull_request]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Test Github variables
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.ref }}          
          echo ${{ github.ref_name }}
          echo ${{ github.head_ref }}

      - name: Auto Generate Changelog
        id: changelog
        run: |
          python3 script.py --tag ${{ github.head_ref }}
      
      - name: Get Changed Files
        id: changed-files
        if: ${{ steps.extract-version.outputs.version }}
        uses: tj-actions/changed-files@v31

      - name: Auto Commit Updated Changelog
        id: auto-commit-push
        if: ${{ steps.changed-files.outputs.any_changed }} && ${{ steps.extract-version.outputs.version }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update: CHANGELOG.md"
          file_pattern: "CHANGELOG.md"