name: Auto Release

on: [pull_request]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Test Github variables
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.ref }}          
          echo ${{ github.ref_name }}
          echo ${{ github.head_ref }}

      - name: Auto Generate Changelog
        run:
          echo $(git log --oneline --format=" * %s" v1..${{github.head_ref}})
          