name: Auto Release

on: [push, pull_request]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Sparse-checkout
        uses: lablup/sparse-checkout@v1
  
      - name: Get Tag
        run: |
          echo "$(git rev-parse --abbrev-ref HEAD)"
          echo "$(git rev-parse --abbrev-ref HEAD~1)"
          
          echo "$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))"