name: Auto Release

on:
  push:
  pull_request:
    types:
      - closed

jobs:
  tagging:
    runs-on: ubuntu-latest
    if: ${{ contains(github.base_ref, 'master') || contains(github.ref, 'master') }}
    steps:
      - name: Test
        run: echo "test"
