name: Auto Release

on: [push, pull_request]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: First
        id: first
        run: |
          version=$(echo '${{ github.event.pull_request.title }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
          echo "::set-output name=version::$version"

      - name: Test
        if: ${{ steps.first.outputs.version }}
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}