name: Auto Release

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0-59 * * * *'


jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Cron Activated?
        run: echo "cron activated"
