name: Sample Workflow

on:
  push:
    branches:
      - master

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "fuc"

          ARGS=$(git log --oneline -1 --format="%s")
          echo "$ARGS"
          echo $ARGS

          echo "$(git log --oneline -1 --format="%s")"

          echo "$(git rev-list --tags --max-count=1)"
          echo "$(git describe --tags `git rev-list --tags --max-count=1`)"
          
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: $(git describe --tags `git rev-list --tags --max-count=1`)
