name: Auto Release

on: [pull_request]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Test Github variables
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.ref }}          
          echo ${{ github.ref_name }}
          echo ${{ github.head_ref }}

      - name: Run Test Script
        run: |
          TAGS_LIST=($(python3 script.py))
          echo "$TAGS_LIST[0]"
          echo "$TAGS_LIST[1]"
          echo "$TAGS_LIST[2]"