name: Auto Release

on: [pull_request]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Test Github variables
        id: test
        run: |
          echo ${{ github.event.action == 'closed' }}
          echo ${{ github.event.pull_request.merged }}

      - name: Condition Check
        if: ${{ github.event.action == 'closed'}} && {{ steps.test.outputs.version }}
        run: |
          echo ${{ github.event.action == 'closed' }}
          echo ${{ github.event.pull_request.merged }}

