name: Sample Workflow

on:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'


jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - id: latest
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo Step1
        run: |
          echo ${{ steps.latest.outputs.tag_name }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.latest.outputs.tag_name }}

      - name: Echo Step2
        run: |
          echo "$(git rev-list --tags --max-count=1)"
          echo "$(git describe --tags `git rev-list --tags --max-count=1`)"
