name: Auto Release

on: [push, pull_request]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: First
        id: first
        run: |
          echo "1.1.1"

      - name: Test
        if: ${{ steps.first.outputs.version }}
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}