name: Sample Workflow

on:
  push:
    branches:
      - master

jobs:
  checkout-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Fetch Latest Tag
        id: fetch-tag
        run: |
          echo "debugging statement"
          TAG=$(git rev-list --tags --skip=0 --max-count=1)
          echo "$TAG"
          echo "::set-output name=ref::$TAG"
      
      - run: echo "${{ steps.fetch-tag.outputs.ref }}"

      - name: Checkout with Hash
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.fetch-tag.outputs.ref }}
