name: Sample Workflow

on:
  push:
    branches:
      - master

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Latest Release
        id: latest-release
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "${{ steps.latest-release.outputs.tag-name }}"

      - name: Checkout Latest Release source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.latest-release.outputs.tag-name }}

