name: Auto Release

on: [push, pull_request]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.ref }}          
          echo ${{ github.head_ref }}